server:
  port: 8082
  servlet:
    context-path: /cmfz
    jsp-servlet:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cmfz
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200MB
  redis:
    host: 192.168.66.129
    port: 6379

mybatis:
  type-aliases-package: com.mp.cmfz.entity
  mapper-locations: mapper/*.xml



#logging:
#  level:
#    root: info
#    com.mp.cmfz.dao: debug
